### ISSUE TITLE
Martin

### ISSUE THREAD

**Issue by bwmoths** [hdus/SRTM-Downloader#2]
Hi, I am unable to get the QGIS Plugin to work ! Python error reported, please see error report below.
Am I doing something wrong ?
Martin

An error has occurred while executing Python code: 

URLError: 
Traceback (most recent call last):
  File "C:/Users/Martin/.qgis2/python/plugins\SRTM-Downloader\srtm_downloader_dialog_base.py", line 213, in on_btn_download_clicked
    self.get_tiles(self.username, self.password)
  File "C:/Users/Martin/.qgis2/python/plugins\SRTM-Downloader\srtm_downloader_dialog_base.py", line 155, in get_tiles
    u = urllib.request.urlopen(request)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\future\backports\urllib\request.py", line 171, in urlopen
    return opener.open(url, data, timeout)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\future\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\future\backports\urllib\request.py", line 517, in _open
    'unknown_open', req)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\future\backports\urllib\request.py", line 1353, in unknown_open
    raise URLError('unknown url type: %s' % type)
URLError: 

Python version: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
QGIS version: 2.18.15 Las Palmas, ac2d111ed1 

Python Path:
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins\processing
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python
C:/Users/Martin/.qgis2/python
C:/Users/Martin/.qgis2/python/plugins
C:/PROGRA~1/QGIS2~1.18/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS2~1.18\bin\python27.zip
C:\PROGRA~1\QGIS2~1.18\apps\Python27\DLLs
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\plat-win
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\lib-tk
C:\PROGRA~1\QGIS2~1.18\bin
C:\PROGRA~1\QGIS2~1.18\apps\Python27
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Pythonwin
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win-amd64.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\wx-2.8-msw-unicode
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlrd-0.9.2-py2.7.egg
C:\PROGRA~1\QGIS2~1.18\apps\Python27\lib\site-packages\xlwt-0.7.5-py2.7.egg
C:/Users/Martin/.qgis2//python
C:\Users\Martin\.qgis2\python\plugins\mmqgis/forms
C:\Users\Martin\.qgis2\python\plugins
C:\Users\Martin\.qgis2\python\plugins
F:/GIS/UKProjects/SthWiltshire

**Comment by bwmoths** [comment]
Latest update has solved my problem. All working fine now thank you.
Martin
