### ISSUE TITLE
'About' button produces a Python error

### ISSUE THREAD

**Issue by AlisterH** [hdus/SRTM-Downloader#3]
Using on Windows it works well except the about button:
````
Traceback (most recent call last):
			  File "C:/Users/alistair/.qgis2/python/plugins\SRTM-Downloader\srtm_downloader_dialog_base.py", line 198, in on_btn_about_clicked
			    self.about = About()
			  File "C:/Users/alistair/.qgis2/python/plugins\SRTM-Downloader\about\do_about.py", line 44, in __init__
			    aboutString = pystring( self.metadata.description() )
			NameError: global name 'pystring' is not defined

**Comment by hdus** [comment]
fixed in 1.1.2
